spring.application.name=api-gateway
server.port=8080

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# JWT Secret
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

# --- Routes Configuration ---

# 1. Auth Service Route
spring.cloud.gateway.routes[0].id=user-auth-service
spring.cloud.gateway.routes[0].uri=lb://USER-AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# 2. Employee Service Route
spring.cloud.gateway.routes[1].id=employee-service
spring.cloud.gateway.routes[1].uri=lb://EMPLOYEE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/employees/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# 3. Pet Profile Service Route
spring.cloud.gateway.routes[2].id=pet-profile-service
spring.cloud.gateway.routes[2].uri=lb://PET-PROFILE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/pets/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# 4. Appointment Service Route
spring.cloud.gateway.routes[3].id=appointment-service
spring.cloud.gateway.routes[3].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/appointments/**
spring.cloud.gateway.routes[3].filters[0]=AuthenticationFilter

# 5. Medical Record Service Route
spring.cloud.gateway.routes[4].id=medical-record-service
spring.cloud.gateway.routes[4].uri=lb://MEDICAL-RECORD-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/medical-records/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter

# 6. Vaccination Service Route
spring.cloud.gateway.routes[5].id=vaccination-service
spring.cloud.gateway.routes[5].uri=lb://VACCINATION-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/vaccinations/**
spring.cloud.gateway.routes[5].filters[0]=AuthenticationFilter