spring.application.name=api-gateway
server.port=8080

# Eureka ekata connect wima
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Auth Service Route
#spring.cloud.gateway.routes[0].id=user-auth-service
#spring.cloud.gateway.routes[0].uri=lb://USER-AUTH-SERVICE
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
#
## Pet Profile Service Route
#spring.cloud.gateway.routes[1].id=pet-profile-service
#spring.cloud.gateway.routes[1].uri=lb://PET-PROFILE-SERVICE
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/pets/**